# see: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/ci/yaml/README.md
# see: https://gitlab.com/gitlab-org/gitlab-ce/issues/3423

before_script:
  - export OSS_BUILD_REF_BRANCH="develop"
  - export OSS_BUILD_CONFIG_REF_BRANCH="develop"
  - export GIT_REPO_OWNER="home1-oss"                   # 所构建项目owner
  - export OSS_BUILD_GIT_SERVICE="https://github.com"  # oss-build项目地址
  - export OSS_BUILD_GIT_REPO_OWNER="home1-oss"        # oss-build ownner

stages:
- analysis
- test_and_build
- deploy

sonar:
  stage: analysis
  script:
  - echo "on_analysis"
  - bash ci.sh analysis

on_every_push:
  stage: test_and_build
  script:
  - echo "on_every_push"
  - bash ci.sh test_and_build
  artifacts:
    expire_in: 1 day
    untracked: true

on_develop_push:
  stage: deploy
  script:
  - echo "on_develop_push"
  - bash ci.sh publish_snapshot
  - bash ci.sh publish_maven_site
  only:
  - develop
  dependencies:
  - on_every_push

on_master_push:
  stage: deploy
  script:
  - echo "on_master_push"
  - bash ci.sh publish_release
  only:
  - master
  dependencies:
  - on_every_push
  artifacts:
    paths:
    - "**/target/*.jar"
    - "**/target/*.war"

on_release_tag:
  stage: deploy
  script:
  - echo "on_release_tag"
  - bash ci.sh publish_release_tag
  only:
  - /^release.+$/
