addons:
  apt:
    packages:
    - gnupg
    - gnupg2
    - graphviz
    - openssl
before_install:
- wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
- unzip -qq apache-maven-3.3.9-bin.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
branches:
  only:
  - master
  - develop
  - /^feature\/.*$/
  - /^hotfix\/.*$/
  - /^release\/.*$/
  - /^v\d+\.\d+(\.\d+)?(-\S*)?/
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.gradle"
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"

dist: trusty
env:
  global:
  - BUILD_SITE=true
  - INFRASTRUCTURE=github
  - LIB_CI_SCRIPT=https://github.com/home1-oss/oss-build/raw/master/src/main/ci-script/lib_ci.sh
  - ORIGIN_REPO_SLUG=home1-oss/oss-todomvc
  - MAVEN_SKIP_RC=true
group: edge
install: true
jdk:
- oraclejdk8
language: java
script:
- bash ci.sh analysis clean test_and_build publish_site
services:
- docker
sudo: required
